In [57]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.ensemble import RandomForestRegressor

pd.options.display.float_format = '{:,.2f}'.format

# setup interactive notebook mode
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from IPython.display import display, HTML

In [58]:
arrivalData = pd.read_excel("C:/Users/HS/OneDrive - Syracuse University/Anurima-Masters/Spring 2023/Intro To ML/PROJECTS/2022 airlines data/Arrivals_details.xlsx",parse_dates=['Date (MM/DD/YYYY)','Scheduled Arrival Time','Actual Arrival Time'])

departureData = pd.read_excel("C:/Users/HS/OneDrive - Syracuse University/Anurima-Masters/Spring 2023/Intro To ML/PROJECTS/2022 airlines data/final departures-details.xlsx",parse_dates=['Date (MM/DD/YYYY)','Scheduled departure time','Actual departure time','Wheels-off time'])


arrivalData
departureData
arrivalData.dtypes
departureData.dtypes

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,UA,2022-01-10,604,N843UA,DEN,2023-04-11 15:09:00,2023-04-11 15:04:00,200,198,-5,14:59:00,5,0,0,0,0,0
1,UA,2022-01-10,1917,N899UA,ORD,2023-04-11 16:57:00,2023-04-11 16:54:00,107,108,-3,16:50:00,4,0,0,0,0,0
2,UA,2022-01-10,1998,N834UA,ORD,2023-04-11 21:18:00,2023-04-11 21:01:00,117,106,-17,20:55:00,6,0,0,0,0,0
3,UA,2022-01-10,2198,N854UA,IAD,2023-04-11 23:31:00,2023-04-11 23:52:00,71,65,21,23:48:00,4,21,0,0,0,0
4,UA,2022-02-10,604,N402UA,DEN,2023-04-11 15:09:00,2023-04-11 14:55:00,200,191,-14,14:50:00,5,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,UA,2022-12-30,1998,N872UA,ORD,2023-04-11 21:07:00,2023-04-11 20:56:00,113,105,-11,20:51:00,5,0,0,0,0,0
267,UA,2022-12-30,2488,N27251,EWR,2023-04-11 23:14:00,2023-04-11 23:07:00,75,50,-7,23:03:00,4,0,0,0,0,0
268,UA,2022-12-31,604,N801UA,DEN,2023-04-11 14:58:00,2023-04-11 14:46:00,193,178,-12,14:39:00,7,0,0,0,0,0
269,UA,2022-12-31,1998,N23707,ORD,2023-04-11 21:08:00,2023-04-11 20:44:00,113,98,-24,20:40:00,4,0,0,0,0,0
270,UA,2022-12-31,2488,N37427,EWR,2023-04-11 23:14:00,2023-04-11 00:46:00,75,73,92,00:40:00,6,92,0,0,0,0

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes),Source Airport
0,UA,2022-01-10,2198,N854UA,SYR,2023-04-11 22:20:00,2023-04-11 22:47:00,71,65,27,2023-04-11 23:01:00,14,21,0,0,0,0,IAD
1,UA,2022-02-10,2198,N854UA,SYR,2023-04-11 22:20:00,2023-04-11 22:21:00,71,71,1,2023-04-11 22:38:00,17,0,0,0,0,0,IAD
2,UA,2022-03-10,2198,N830UA,SYR,2023-04-11 22:20:00,2023-04-11 22:12:00,71,69,-8,2023-04-11 22:26:00,14,0,0,0,0,0,IAD
3,UA,2022-04-10,2198,N876UA,SYR,2023-04-11 22:20:00,2023-04-11 22:23:00,71,67,3,2023-04-11 22:37:00,14,0,0,0,0,0,IAD
4,UA,2022-05-10,2198,N832UA,SYR,2023-04-11 22:20:00,2023-04-11 22:16:00,71,75,-4,2023-04-11 22:32:00,16,0,0,0,0,0,IAD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,UA,2022-12-27,1998,N401UA,SYR,2023-04-11 18:14:00,2023-04-11 18:18:00,113,98,4,2023-04-11 18:32:00,14,0,0,0,0,0,ORD
267,UA,2022-12-28,1998,N825UA,SYR,2023-04-11 18:14:00,2023-04-11 18:55:00,113,101,41,2023-04-11 19:13:00,18,5,0,0,0,24,ORD
268,UA,2022-12-29,1998,N894UA,SYR,2023-04-11 18:14:00,2023-04-11 18:31:00,113,117,17,2023-04-11 19:01:00,30,17,0,4,0,0,ORD
269,UA,2022-12-30,1998,N872UA,SYR,2023-04-11 18:14:00,2023-04-11 18:11:00,113,105,-3,2023-04-11 18:33:00,22,0,0,0,0,0,ORD
270,UA,2022-12-31,1998,N23707,SYR,2023-04-11 18:15:00,2023-04-11 18:06:00,113,98,-9,2023-04-11 18:22:00,16,0,0,0,0,0,ORD

Carrier Code                                        object
Date (MM/DD/YYYY)                           datetime64[ns]
Flight Number                                        int64
Tail Number                                         object
Origin Airport                                      object
Scheduled Arrival Time                      datetime64[ns]
Actual Arrival Time                         datetime64[ns]
Scheduled Elapsed Time (Minutes)                     int64
Actual Elapsed Time (Minutes)                        int64
Arrival Delay (Minutes)                              int64
Wheels-on Time                                      object
Taxi-In time (Minutes)                               int64
Delay Carrier (Minutes)                              int64
Delay Weather (Minutes)                              int64
Delay National Aviation System (Minutes)             int64
Delay Security (Minutes)                             int64
Delay Late Aircraft Arrival (Minutes)                int64
dtype: object

Carrier Code                                        object
Date (MM/DD/YYYY)                           datetime64[ns]
Flight Number                                        int64
Tail Number                                         object
Destination Airport                                 object
Scheduled departure time                    datetime64[ns]
Actual departure time                       datetime64[ns]
Scheduled elapsed time (Minutes)                     int64
Actual elapsed time (Minutes)                        int64
Departure delay (Minutes)                            int64
Wheels-off time                             datetime64[ns]
Taxi-Out time (Minutes)                              int64
Delay Carrier (Minutes)                              int64
Delay Weather (Minutes)                              int64
Delay National Aviation System (Minutes)             int64
Delay Security (Minutes)                             int64
Delay Late Aircraft Arrival (Minutes)                int64
Source Airport                                      object
dtype: object

In [59]:
flightData = pd.merge(arrivalData, departureData, on = ['Date (MM/DD/YYYY)','Flight Number','Tail Number','Carrier Code'])

flightData.drop(columns=['Tail Number','Carrier Code','Source Airport','Destination Airport'],inplace=True)
flightData.dtypes
flightData

Date (MM/DD/YYYY)                             datetime64[ns]
Flight Number                                          int64
Origin Airport                                        object
Scheduled Arrival Time                        datetime64[ns]
Actual Arrival Time                           datetime64[ns]
Scheduled Elapsed Time (Minutes)                       int64
Actual Elapsed Time (Minutes)                          int64
Arrival Delay (Minutes)                                int64
Wheels-on Time                                        object
Taxi-In time (Minutes)                                 int64
Delay Carrier (Minutes)_x                              int64
Delay Weather (Minutes)_x                              int64
Delay National Aviation System (Minutes)_x             int64
Delay Security (Minutes)_x                             int64
Delay Late Aircraft Arrival (Minutes)_x                int64
Scheduled departure time                      datetime64[ns]
Actual departure time                         datetime64[ns]
Scheduled elapsed time (Minutes)                       int64
Actual elapsed time (Minutes)                          int64
Departure delay (Minutes)                              int64
Wheels-off time                               datetime64[ns]
Taxi-Out time (Minutes)                                int64
Delay Carrier (Minutes)_y                              int64
Delay Weather (Minutes)_y                              int64
Delay National Aviation System (Minutes)_y             int64
Delay Security (Minutes)_y                             int64
Delay Late Aircraft Arrival (Minutes)_y                int64
dtype: object

,Date (MM/DD/YYYY),Flight Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),...,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes)_y,Delay Weather (Minutes)_y,Delay National Aviation System (Minutes)_y,Delay Security (Minutes)_y,Delay Late Aircraft Arrival (Minutes)_y
0,2022-01-10,604,DEN,2023-04-11 15:09:00,2023-04-11 15:04:00,200,198,-5,14:59:00,5,...,200,198,-3,2023-04-11 10:03:00,17,0,0,0,0,0
1,2022-01-10,1917,ORD,2023-04-11 16:57:00,2023-04-11 16:54:00,107,108,-3,16:50:00,4,...,107,108,-4,2023-04-11 14:32:00,26,0,0,0,0,0
2,2022-01-10,1998,ORD,2023-04-11 21:18:00,2023-04-11 21:01:00,117,106,-17,20:55:00,6,...,117,106,-6,2023-04-11 18:35:00,20,0,0,0,0,0
3,2022-01-10,2198,IAD,2023-04-11 23:31:00,2023-04-11 23:52:00,71,65,21,23:48:00,4,...,71,65,27,2023-04-11 23:01:00,14,21,0,0,0,0
4,2022-02-10,604,DEN,2023-04-11 15:09:00,2023-04-11 14:55:00,200,191,-14,14:50:00,5,...,200,191,-5,2023-04-11 09:58:00,14,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,2022-12-30,1998,ORD,2023-04-11 21:07:00,2023-04-11 20:56:00,113,105,-11,20:51:00,5,...,113,105,-3,2023-04-11 18:33:00,22,0,0,0,0,0
267,2022-12-30,2488,EWR,2023-04-11 23:14:00,2023-04-11 23:07:00,75,50,-7,23:03:00,4,...,75,50,18,2023-04-11 22:31:00,14,0,0,0,0,0
268,2022-12-31,604,DEN,2023-04-11 14:58:00,2023-04-11 14:46:00,193,178,-12,14:39:00,7,...,193,178,3,2023-04-11 10:00:00,12,0,0,0,0,0
269,2022-12-31,1998,ORD,2023-04-11 21:08:00,2023-04-11 20:44:00,113,98,-24,20:40:00,4,...,113,98,-9,2023-04-11 18:22:00,16,0,0,0,0,0
270,2022-12-31,2488,EWR,2023-04-11 23:14:00,2023-04-11 00:46:00,75,73,92,00:40:00,6,...,75,73,94,2023-04-11 00:03:00,30,92,0,0,0,0

In [61]:
flightData['Scheduled Arrival Time(hour)'] = flightData['Scheduled Arrival Time'].dt.hour
flightData['Scheduled Arrival Time(minutes)'] = flightData['Scheduled Arrival Time'].dt.minute

flightData['Scheduled departure time(hour)'] = flightData['Scheduled departure time'].dt.hour
flightData['Scheduled departure time(minutes)'] = flightData['Scheduled departure time'].dt.minute

flightData['Actual Arrival Time(hour)'] = flightData['Actual Arrival Time'].dt.hour
flightData['Actual Arrival Time(minutes)'] = flightData['Actual Arrival Time'].dt.minute

flightData['Actual departure time(hour)'] = flightData['Actual departure time'].dt.hour
flightData['Actual departure time(minutes)'] = flightData['Actual departure time'].dt.minute

flightData['Wheels-off time(hour)'] = flightData['Wheels-off time'].dt.hour
flightData['Wheels-off time(minutes)'] = flightData['Wheels-off time'].dt.minute

flightData.drop(columns=['Date (MM/DD/YYYY)','Scheduled Arrival Time','Actual Arrival Time','Scheduled departure time','Actual departure time','Wheels-off time','Wheels-on Time'],inplace=True)
flightData.dtypes

Flight Number                                  int64
Origin Airport                                object
Scheduled Elapsed Time (Minutes)               int64
Actual Elapsed Time (Minutes)                  int64
Arrival Delay (Minutes)                        int64
Taxi-In time (Minutes)                         int64
Delay Carrier (Minutes)_x                      int64
Delay Weather (Minutes)_x                      int64
Delay National Aviation System (Minutes)_x     int64
Delay Security (Minutes)_x                     int64
Delay Late Aircraft Arrival (Minutes)_x        int64
Scheduled elapsed time (Minutes)               int64
Actual elapsed time (Minutes)                  int64
Departure delay (Minutes)                      int64
Taxi-Out time (Minutes)                        int64
Delay Carrier (Minutes)_y                      int64
Delay Weather (Minutes)_y                      int64
Delay National Aviation System (Minutes)_y     int64
Delay Security (Minutes)_y                     int64
Delay Late Aircraft Arrival (Minutes)_y        int64
Scheduled Arrival Time(hour)                   int64
Scheduled Arrival Time(minutes)                int64
Scheduled departure time(hour)                 int64
Scheduled departure time(minutes)              int64
Actual Arrival Time(hour)                      int64
Actual Arrival Time(minutes)                   int64
Actual departure time(hour)                    int64
Actual departure time(minutes)                 int64
Wheels-off time(hour)                          int64
Wheels-off time(minutes)                       int64
dtype: object

In [62]:
from sklearn.preprocessing import OneHotEncoder

def get_ohe(df, col):
    ohe = OneHotEncoder(drop='first', handle_unknown='error', sparse=False, dtype='int')
    ohe.fit(df[[col]])
    temp_df = pd.DataFrame(data=ohe.transform(df[[col]]), columns=ohe.get_feature_names_out())
    # If you have a newer version, replace with columns=ohe.get_feature_names_out()
    df.drop(columns=[col], axis=1, inplace=True)
    df = pd.concat([df.reset_index(drop=True), temp_df], axis=1)
    return df
Final_flightData = get_ohe(flightData, 'Origin Airport')

Final_flightData

,Flight Number,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Taxi-In time (Minutes),Delay Carrier (Minutes)_x,Delay Weather (Minutes)_x,Delay National Aviation System (Minutes)_x,Delay Security (Minutes)_x,Delay Late Aircraft Arrival (Minutes)_x,...,Scheduled departure time(minutes),Actual Arrival Time(hour),Actual Arrival Time(minutes),Actual departure time(hour),Actual departure time(minutes),Wheels-off time(hour),Wheels-off time(minutes),Origin Airport_EWR,Origin Airport_IAD,Origin Airport_ORD
0,604,200,198,-5,5,0,0,0,0,0,...,49,15,4,9,46,10,3,0,0,0
1,1917,107,108,-3,4,0,0,0,0,0,...,10,16,54,14,6,14,32,0,0,1
2,1998,117,106,-17,6,0,0,0,0,0,...,21,21,1,18,15,18,35,0,0,1
3,2198,71,65,21,4,21,0,0,0,0,...,20,23,52,22,47,23,1,0,1,0
4,604,200,191,-14,5,0,0,0,0,0,...,49,14,55,9,44,9,58,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
266,1998,113,105,-11,5,0,0,0,0,0,...,14,20,56,18,11,18,33,0,0,1
267,2488,75,50,-7,4,0,0,0,0,0,...,59,23,7,22,17,22,31,1,0,0
268,604,193,178,-12,7,0,0,0,0,0,...,45,14,46,9,48,10,0,0,0,0
269,1998,113,98,-24,4,0,0,0,0,0,...,15,20,44,18,6,18,22,0,0,1
270,2488,75,73,92,6,92,0,0,0,0,...,59,0,46,23,33,0,3,1,0,0

In [63]:
X_train, X_test, y_train, y_test = train_test_split(Final_flightData.drop(columns = ['Arrival Delay (Minutes)']), Final_flightData['Arrival Delay (Minutes)'], test_size=0.05, random_state=35)

X_train
X_test
y_train
y_test

,Flight Number,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Taxi-In time (Minutes),Delay Carrier (Minutes)_x,Delay Weather (Minutes)_x,Delay National Aviation System (Minutes)_x,Delay Security (Minutes)_x,Delay Late Aircraft Arrival (Minutes)_x,Scheduled elapsed time (Minutes),...,Scheduled departure time(minutes),Actual Arrival Time(hour),Actual Arrival Time(minutes),Actual departure time(hour),Actual departure time(minutes),Wheels-off time(hour),Wheels-off time(minutes),Origin Airport_EWR,Origin Airport_IAD,Origin Airport_ORD
124,1998,114,105,6,0,0,0,0,0,114,...,14,21,22,18,37,18,53,0,0,1
117,1917,107,99,6,0,0,0,0,0,107,...,0,16,34,13,55,14,6,0,0,1
258,2488,75,59,6,48,0,0,0,10,75,...,59,0,12,23,13,23,31,1,0,0
102,2198,71,67,4,0,0,0,0,0,71,...,20,23,20,22,13,22,28,0,1,0
193,604,194,181,5,0,0,0,0,0,194,...,43,14,37,9,36,9,48,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,604,194,186,5,0,0,0,0,0,194,...,43,14,45,9,39,9,51,0,0,0
232,604,193,192,4,64,0,0,0,0,193,...,48,16,5,10,53,11,8,0,0,0
249,2488,75,71,5,91,0,0,0,289,75,...,11,5,46,4,35,5,7,1,0,0
33,604,200,209,6,0,0,0,0,0,200,...,49,15,6,9,37,10,4,0,0,0
201,604,194,169,5,0,0,0,0,0,194,...,43,14,29,9,40,9,53,0,0,0

,Flight Number,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Taxi-In time (Minutes),Delay Carrier (Minutes)_x,Delay Weather (Minutes)_x,Delay National Aviation System (Minutes)_x,Delay Security (Minutes)_x,Delay Late Aircraft Arrival (Minutes)_x,Scheduled elapsed time (Minutes),...,Scheduled departure time(minutes),Actual Arrival Time(hour),Actual Arrival Time(minutes),Actual departure time(hour),Actual departure time(minutes),Wheels-off time(hour),Wheels-off time(minutes),Origin Airport_EWR,Origin Airport_IAD,Origin Airport_ORD
78,604,200,209,6,0,0,0,0,0,200,...,49,15,13,9,44,10,2,0,0,0
17,1917,107,111,5,0,0,0,0,0,107,...,0,16,43,13,52,14,15,0,0,1
255,1998,113,105,6,41,0,0,0,0,113,...,14,21,48,19,3,19,18,0,0,1
23,2198,71,65,5,0,0,0,0,0,71,...,20,23,17,22,12,22,26,0,1,0
267,2488,75,50,4,0,0,0,0,0,75,...,59,23,7,22,17,22,31,1,0,0
210,1998,112,106,5,0,0,0,0,0,112,...,47,22,25,19,39,20,7,0,0,1
3,2198,71,65,4,21,0,0,0,0,71,...,20,23,52,22,47,23,1,0,1,0
182,604,194,177,5,0,0,0,0,0,194,...,43,15,9,10,12,10,22,0,0,0
212,604,194,183,4,0,0,0,0,0,194,...,43,14,45,9,42,9,56,0,0,0
177,604,194,188,4,0,0,0,0,0,194,...,43,14,52,9,44,10,1,0,0,0
72,1998,117,120,8,0,0,0,0,0,117,...,21,21,14,18,14,18,39,0,0,1
94,2198,71,65,5,0,0,0,0,0,71,...,20,23,18,22,13,22,28,0,1,0
247,604,193,197,7,15,0,4,0,0,193,...,45,15,17,10,0,10,15,0,0,0
25,604,200,191,5,0,0,0,0,0,200,...,49,15,12,10,1,10,17,0,0,0

124     14
117    -13
258     58
102    -11
193    -20
      ...
139    -12
232     64
249    380
33      -3
201    -28
Name: Arrival Delay (Minutes), Length: 257, dtype: int64

78      4
17     -4
255    41
23    -14
267    -7
210   -14
3      21
182    12
212   -12
177    -5
72     -4
94    -13
247    19
25      3
Name: Arrival Delay (Minutes), dtype: int64

In [64]:
if True: 
    from sklearn.preprocessing import StandardScaler
    sc = StandardScaler()
    X_train = pd.DataFrame(sc.fit_transform(X_train), columns = X_train.columns, index = X_train.index)
    X_test = pd.DataFrame(sc.transform(X_test), columns = X_test.columns, index = X_test.index)

In [65]:
model1 = LinearRegression(fit_intercept = True)
model1.fit(X_train, y_train) 

# The following gives the R-square score
model1.score(X_train, y_train) 

# This is the coefficient Beta_1, ..., Beta_17
model1.coef_

# This is the coefficient Beta_0
model1.intercept_

LinearRegression()

0.9981533050201896

array([ 9.38111534e-01, -2.35462983e+01,  2.06653600e+01,  5.11799895e-01,
        5.25422136e-01,  5.58982293e-01,  7.44745803e-01,  4.26325641e-14,
       -1.00170730e+00, -2.35462983e+01,  2.06653600e+01,  6.87985819e+01,
       -1.69066104e-01,  5.25422136e-01,  5.58982293e-01,  7.44745803e-01,
        0.00000000e+00, -1.00170730e+00,  4.27444739e+00, -1.36094616e-01,
        4.35353253e+00,  1.49626074e+00, -1.32433971e+00, -4.61238348e-01,
       -1.28578577e+01, -1.01335443e+00,  2.67183905e+00, -2.47588261e-01,
       -7.16614947e+00, -6.72524216e+00, -7.44658415e+00])

7.155642023346294

In [66]:
test_output_a = pd.DataFrame(model1.predict(X_test), index = X_test.index, columns = ['pred_Arrival Delay'])
# When extending to multiple features remove .array.reshape(-1, 1)
test_output_a.head()

     pred_Arrival Delay
78                 2.76
17                -6.28
255               41.25
23               -13.19
267               -2.46

In [67]:
test_output_a = pd.DataFrame(model1.predict(X_test), index = X_test.index, columns = ['pred_Arrival Delay'])
test_output_a = test_output_a.merge(y_test, left_index = True, right_index = True)
test_output_a.head()
mean_absolute_error = abs(test_output_a['pred_Arrival Delay'] - test_output_a['Arrival Delay (Minutes)']).mean()
print('Mean absolute error is :',mean_absolute_error)
error_ratio_a=mean_absolute_error/y_test.mean()
print('Error ratio is:',error_ratio_a)

     pred_Arrival Delay  Arrival Delay (Minutes)
78                 2.76                        4
17                -6.28                       -4
255               41.25                       41
23               -13.19                      -14
267               -2.46                       -7

Mean absolute error is : 1.363926422236678
Error ratio is: 0.7072211078264257