In [4]:
# Generic inputs for most ML tasks
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso

from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
# from sklearn.ensemble import HistGradientBoostingRegressor
import xgboost as xgb

pd.options.display.float_format = '{:,.2f}'.format

# setup interactive notebook mode
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from IPython.display import display, HTML

In [5]:

# Original data

Arrival_data = pd.read_csv(r"C:\Users\VIKAS\Documents\Intro to ML\Project\datasets\data\Arrival_data.csv")

Departure_data = pd.read_csv(r"C:\Users\VIKAS\Documents\Intro to ML\Project\datasets\data\Departure_data.csv")

SYR_weather = pd.read_excel(r"C:\Users\VIKAS\Documents\Intro to ML\Project\datasets\data\SYR_weather_2023.xlsx")






Arrival_data = Arrival_data[Arrival_data['Origin Airport'].isin({'ORD', 'JFK', 'MCO'})]
Arrival_data = Arrival_data[['Carrier Code', 'Date (MM/DD/YYYY)', 'Flight Number', 'Origin Airport', 
                             'Scheduled Arrival Time', 'Actual Arrival Time','Scheduled Elapsed Time (Minutes)', 
                             'Actual Elapsed Time (Minutes)', 'Arrival Delay (Minutes)']]





Departure_data = Departure_data[Departure_data['Destination Airport'].isin({'SYR'})]
Departure_data = Departure_data[['Carrier Code', 'Date (MM/DD/YYYY)', 'Flight Number','Destination Airport',
                                'Scheduled departure time']]




Flight_data = pd.merge(Arrival_data, Departure_data, on = ['Carrier Code', 'Date (MM/DD/YYYY)', 'Flight Number'])


def categorize_arrival_delay(delay):
    if delay <= -5:
        return 'Early'
    elif delay <= 5:
        return 'On Time'
    else:
        return 'Late'
Flight_data['Arrival_Delay_Status'] = Flight_data['Arrival Delay (Minutes)'].apply(categorize_arrival_delay)


Flight_data = Flight_data[Flight_data['Flight Number'].isin({538, 3402, 116, 5340, 491, 656})]


Flight_data['Date (MM/DD/YYYY)'] = pd.to_datetime(Flight_data['Date (MM/DD/YYYY)'])
SYR_weather['datetime'] = pd.to_datetime(SYR_weather['datetime'])
Flight_weather = pd.merge(Flight_data, SYR_weather, left_on='Date (MM/DD/YYYY)', right_on='datetime')
Flight_weather.drop('datetime', axis=1, inplace=True)

In [3]:
# Flight_weather.to_csv('Flight_weather.csv', index = False)

In [ ]:
'''

# testing data1

test_Flight_data1 = pd.read_csv(r"C:\Users\VIKAS\Documents\Intro to ML\Project\datasets\data\test_Flight_data1.csv")

SYR_weather_4 = pd.read_excel(r"C:\Users\VIKAS\Documents\Intro to ML\Project\datasets\data\SYR_weather_4-24.xlsx")

test_Flight_data1['Date (MM/DD/YYYY)'] = pd.to_datetime(test_Flight_data1['Date (MM/DD/YYYY)'])
SYR_weather_4['datetime'] = pd.to_datetime(SYR_weather_4['datetime'])
test_Flight_weather1 = pd.merge(test_Flight_data1, SYR_weather_4, left_on='Date (MM/DD/YYYY)', right_on='datetime')
test_Flight_weather1.drop('datetime', axis=1, inplace=True)

'''

In [2]:
'''

# testing data2

test_Flight_data2 = pd.read_csv(r"C:\Users\VIKAS\Documents\Intro to ML\Project\datasets\data\test_Flight_data2.csv")

SYR_weather_4 = pd.read_excel(r"C:\Users\VIKAS\Documents\Intro to ML\Project\datasets\data\SYR_weather_4-24.xlsx")

test_Flight_data2['Date'] = pd.to_datetime(test_Flight_data2['Date'])
SYR_weather_4['datetime'] = pd.to_datetime(SYR_weather_4['datetime'])
test_Flight_weather2 = pd.merge(test_Flight_data2, SYR_weather_4, left_on='Date', right_on='datetime')
test_Flight_weather2.drop('datetime', axis=1, inplace=True)
'''

In [6]:
Flight_data

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Destination Airport,Scheduled departure time,Arrival_Delay_Status
71,MQ,2023-06-01,3402,ORD,22:32,23:29,110,120,57,SYR,19:42,Late
73,MQ,2023-06-02,3402,ORD,22:32,22:34,110,116,2,SYR,19:42,On Time
75,MQ,2023-06-03,3402,ORD,23:41,23:26,115,107,-15,SYR,20:46,Early
77,MQ,2023-06-04,3402,ORD,22:28,22:28,109,111,0,SYR,19:39,On Time
79,MQ,2023-06-05,3402,ORD,22:28,22:21,109,106,-7,SYR,19:39,Early
...,...,...,...,...,...,...,...,...,...,...,...,...
2900,WN,2023-03-11,491,MCO,13:40,14:07,160,174,27,SYR,11:00,Late
2901,WN,2023-03-18,491,MCO,13:40,14:31,160,197,51,SYR,11:00,Late
2902,WN,2023-03-25,491,MCO,13:40,13:52,160,150,12,SYR,11:00,Late
2903,WN,2023-04-01,491,MCO,13:40,13:42,160,157,2,SYR,11:00,On Time
2904,WN,2023-04-08,491,MCO,13:40,13:33,160,153,-7,SYR,11:00,Early

In [37]:
predict1 = Flight_data[Flight_data['Carrier Code'].isin({'B6'})]
predict2 = Flight_data[Flight_data['Carrier Code'].isin({'9E'})]

In [38]:
predict1

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Destination Airport,Scheduled departure time,Arrival_Delay_Status
555,B6,2023-01-01,116,JFK,14:48,15:11,73,63,23,SYR,13:35,Late
556,B6,2023-01-01,656,MCO,18:28,19:05,163,192,37,SYR,15:45,Late
558,B6,2023-01-02,116,JFK,14:48,16:52,73,75,124,SYR,13:35,Late
559,B6,2023-01-02,656,MCO,18:28,19:36,163,173,68,SYR,15:45,Late
561,B6,2023-01-03,116,JFK,14:33,20:43,73,65,370,SYR,13:20,Late
...,...,...,...,...,...,...,...,...,...,...,...,...
1513,B6,2023-12-29,656,MCO,19:27,19:19,175,148,-8,SYR,16:32,Early
1515,B6,2023-12-30,116,JFK,15:40,15:31,78,73,-9,SYR,14:22,Early
1516,B6,2023-12-30,656,MCO,19:27,19:04,175,154,-23,SYR,16:32,Early
1518,B6,2023-12-31,116,JFK,15:40,15:33,78,61,-7,SYR,14:22,Early
1519,B6,2023-12-31,656,MCO,19:27,18:51,175,148,-36,SYR,16:32,Early

In [39]:
predict2.to_csv("predict2.csv", index = False)

In [40]:
predict2 = pd.read_csv(r"C:\Users\VIKAS\Documents\Intro to ML\Project\predict2.csv")

In [41]:
predict2['Date (MM/DD/YYYY)'] = pd.to_datetime(predict2['Date (MM/DD/YYYY)'])

In [42]:
predict = pd.merge(predict1, predict2, left_on='Date (MM/DD/YYYY)', right_on='Date (MM/DD/YYYY)')
predict

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Destination Airport,...,dep_Flight Number,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,dep_Arrival_Delay_Status
0,B6,2023-03-09,116,JFK,14:43,14:35,73,72,-8,SYR,...,5340,nan,nan,nan,nan,nan,nan,nan,nan,Early
1,B6,2023-03-10,116,JFK,14:43,14:31,73,68,-12,SYR,...,5340,nan,nan,nan,nan,nan,nan,nan,nan,On Time
2,B6,2023-03-11,116,JFK,14:43,15:01,73,71,18,SYR,...,5340,nan,nan,nan,nan,nan,nan,nan,nan,On Time
3,B6,2023-03-12,116,JFK,14:43,16:44,73,76,121,SYR,...,5340,nan,nan,nan,nan,nan,nan,nan,nan,Early
4,B6,2023-03-13,116,JFK,14:43,14:52,73,64,9,SYR,...,5340,nan,nan,nan,nan,nan,nan,nan,nan,Late
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,B6,2023-06-02,656,MCO,19:02,18:46,167,157,-16,SYR,...,5340,nan,nan,nan,nan,nan,nan,nan,nan,On Time
115,B6,2023-06-03,116,JFK,14:42,14:55,72,74,13,SYR,...,5340,nan,nan,nan,nan,nan,nan,nan,nan,Late
116,B6,2023-06-03,656,MCO,19:02,19:59,167,154,57,SYR,...,5340,nan,nan,nan,nan,nan,nan,nan,nan,Late
117,B6,2023-06-04,116,JFK,14:42,14:53,72,68,11,SYR,...,5340,nan,nan,nan,nan,nan,nan,nan,nan,Early
118,B6,2023-06-04,656,MCO,19:02,18:52,167,158,-10,SYR,...,5340,nan,nan,nan,nan,nan,nan,nan,nan,Early

In [43]:
predict.columns

Index(['Carrier Code', 'Date (MM/DD/YYYY)', 'Flight Number', 'Origin Airport',
       'Scheduled Arrival Time', 'Actual Arrival Time',
       'Scheduled Elapsed Time (Minutes)', 'Actual Elapsed Time (Minutes)',
       'Arrival Delay (Minutes)', 'Destination Airport',
       'Scheduled departure time', 'Arrival_Delay_Status', 'dep_Carrier Code',
       'dep_Flight Number', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'dep_Arrival_Delay_Status'],
      dtype='object')

In [44]:
predict = predict[['Carrier Code', 'Date (MM/DD/YYYY)', 'Flight Number', 'Arrival_Delay_Status', 'dep_Carrier Code',
                  'dep_Flight Number', 'dep_Arrival_Delay_Status']]
predict

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Arrival_Delay_Status,dep_Carrier Code,dep_Flight Number,dep_Arrival_Delay_Status
0,B6,2023-03-09,116,Early,9E,5340,Early
1,B6,2023-03-10,116,Early,9E,5340,On Time
2,B6,2023-03-11,116,Late,9E,5340,On Time
3,B6,2023-03-12,116,Late,9E,5340,Early
4,B6,2023-03-13,116,Late,9E,5340,Late
...,...,...,...,...,...,...,...
114,B6,2023-06-02,656,Early,9E,5340,On Time
115,B6,2023-06-03,116,Late,9E,5340,Late
116,B6,2023-06-03,656,Late,9E,5340,Late
117,B6,2023-06-04,116,Late,9E,5340,Early
118,B6,2023-06-04,656,Early,9E,5340,Early

In [45]:
sorted_df = predict.sort_values(by='Arrival_Delay_Status')

In [46]:
sorted_df

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Arrival_Delay_Status,dep_Carrier Code,dep_Flight Number,dep_Arrival_Delay_Status
0,B6,2023-03-09,116,Early,9E,5340,Early
65,B6,2023-05-09,116,Early,9E,5340,On Time
64,B6,2023-05-08,656,Early,9E,5340,Early
62,B6,2023-05-07,656,Early,9E,5340,Late
60,B6,2023-05-06,656,Early,9E,5340,Early
...,...,...,...,...,...,...,...
67,B6,2023-05-10,116,On Time,9E,5340,Early
75,B6,2023-05-14,116,On Time,9E,5340,Early
73,B6,2023-05-13,116,On Time,9E,5340,On Time
9,B6,2023-03-18,116,On Time,9E,5340,Early
16,B6,2023-03-25,116,On Time,9E,5340,Early

In [47]:
sorted_df = sorted_df[sorted_df['Arrival_Delay_Status'].isin({'Early'})]
sorted_df

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Arrival_Delay_Status,dep_Carrier Code,dep_Flight Number,dep_Arrival_Delay_Status
0,B6,2023-03-09,116,Early,9E,5340,Early
65,B6,2023-05-09,116,Early,9E,5340,On Time
64,B6,2023-05-08,656,Early,9E,5340,Early
62,B6,2023-05-07,656,Early,9E,5340,Late
60,B6,2023-05-06,656,Early,9E,5340,Early
56,B6,2023-05-04,116,Early,9E,5340,Early
54,B6,2023-05-02,116,Early,9E,5340,Early
66,B6,2023-05-09,656,Early,9E,5340,On Time
52,B6,2023-04-30,116,Early,9E,5340,Late
49,B6,2023-04-27,116,Early,9E,5340,Early
44,B6,2023-04-22,116,Early,9E,5340,On Time
43,B6,2023-04-21,116,Early,9E,5340,Late
42,B6,2023-04-20,116,Early,9E,5340,Late
41,B6,2023-04-19,116,Early,9E,5340,Late
37,B6,2023-04-15,116,Early,9E,5340,On Time
50,B6,2023-04-28,116,Early,9E,5340,On Time
36,B6,2023-04-14,116,Early,9E,5340,Late
74,B6,2023-05-13,656,Early,9E,5340,On Time
80,B6,2023-05-16,656,Early,9E,5340,Early
114,B6,2023-06-02,656,Early,9E,5340,On Time
113,B6,2023-06-02,116,Early,9E,5340,On Time
112,B6,2023-06-01,656,Early,9E,5340,Early
111,B6,2023-06-01,116,Early,9E,5340,Early
110,B6,2023-05-31,656,Early,9E,5340,Early
108,B6,2023-05-30,656,Early,9E,5340,Early
77,B6,2023-05-15,116,Early,9E,5340,Early
106,B6,2023-05-29,656,Early,9E,5340,Late
101,B6,2023-05-27,116,Early,9E,5340,Early
99,B6,2023-05-26,116,Early,9E,5340,Late
95,B6,2023-05-24,116,Early,9E,5340,Early
90,B6,2023-05-21,656,Early,9E,5340,Early
88,B6,2023-05-20,656,Early,9E,5340,On Time
84,B6,2023-05-18,656,Early,9E,5340,Early
104,B6,2023-05-28,656,Early,9E,5340,Early
35,B6,2023-04-13,116,Early,9E,5340,Early
118,B6,2023-06-04,656,Early,9E,5340,Early
15,B6,2023-03-24,116,Early,9E,5340,Early
32,B6,2023-04-10,116,Early,9E,5340,Early
1,B6,2023-03-10,116,Early,9E,5340,On Time
10,B6,2023-03-19,116,Early,9E,5340,Early
30,B6,2023-04-08,116,Early,9E,5340,Early
26,B6,2023-04-04,116,Early,9E,5340,Late
28,B6,2023-04-06,116,Early,9E,5340,On Time
21,B6,2023-03-30,116,Early,9E,5340,Late